Repository dragonflyoss/nydus, pull requests merged in 2022-07, with the labels that each got.

#544 ctr-remote: note user this ctr is only enhanced for nydus
  contrib/ctr-remote/cmd/main.go
  contrib/ctr-remote/commands/rpull.go
Labels: anolis_test_pass

#545 makefile: add target `install`
  Makefile
Labels: anolis_test_pass

#546 fscache: fix large stargz chunks processing
  rafs/src/metadata/direct_v6.rs
  src/bin/nydus-image/builder/stargz.rs
  src/bin/nydusd/fs_cache.rs
  storage/src/cache/cachedfile.rs
  storage/src/cache/dummycache.rs
  storage/src/cache/filecache/mod.rs
  storage/src/cache/fscache/mod.rs
  storage/src/cache/mod.rs
  storage/src/meta/mod.rs
Labels: anolis_test_pass

#547 doc: add description about estargz and nerdctl support
  README.md
Labels: anolis_test_fail

#548 README.md: fix up leftovers of stargz for fscache
  README.md
Labels: anolis_test_fail

#549 Fix spelling mistakes
  .gitignore
  contrib/nydus-test/framework/distributor.py
  contrib/nydus-test/framework/rafs.py
  contrib/nydus-test/functional-test/test_nydus.py
  contrib/nydus-test/functional-test/test_nydusify.py
  contrib/nydus-test/functional-test/test_snapshotter.py
  contrib/nydus-test/nydus_test_config.py
  storage/src/cache/dummycache.rs
  storage/src/meta/mod.rs
Labels: anolis_test_pass

#550 nydus-image: remove redundant -o short option
  src/bin/nydus-image/main.rs
Labels: anolis_test_pass

#551 rafs: v6 must have local blobcache configured
  rafs/src/fs.rs
Labels: anolis_test_pass

#557 Add a recording for fscache lazy pulling
  docs/nydus-fscache.md
Labels: anolis_test_pass

#558 fscache: no need to clone string
  src/bin/nydusd/fs_cache.rs
Labels: anolis_test_pass

#562 dep: upgrade packages to fix some security vulnerabilities
  Cargo.lock
  Cargo.toml
  contrib/ctr-remote/go.mod
  contrib/ctr-remote/go.sum
  contrib/docker-nydus-graphdriver/go.mod
  contrib/docker-nydus-graphdriver/go.sum
  contrib/nydusify/go.mod
  contrib/nydusify/go.sum
  storage/Cargo.toml
Labels: anolis_test_pass

#566 add basic nydusify conversion case
  contrib/nydus-test/framework/nydusify.py
  contrib/nydus-test/functional-test/test_nydusify.py
  contrib/nydus-test/functional-test/test_stargz.py
  contrib/nydus-test/functional-test/test_stress.py
  src/bin/nydus-image/core/node.rs
Labels: anolis_test_pass

#567 nydus-test: ignore missing backend_proxy_url
  contrib/nydus-test/framework/nydus_anchor.py
Labels: anolis_test_pass

#574 ci: don't run Convert Top Docker Hub Images job on forked repos
  .github/workflows/convert.yml
Labels: anolis_test_pass

#529 nydusify: Add fs-version args for pack subcommand
  contrib/nydusify/cmd/nydusify.go
  contrib/nydusify/pkg/packer/packer.go
Labels: anolis_test_pass

#577 Add layered image conversion to IT workflow and replace storage backend with BACKEND_PROXY
  .github/workflows/it.yml
  contrib/nydus-test/framework/rafs.py
  contrib/nydus-test/functional-test/test_layered_image.py
Labels: anolis_test_pass

#578 backend-proxy: don't panic if address already binded
  contrib/nydus-backend-proxy/src/main.rs
Labels: anolis_test_pass

#581 Doc: make sure snapshotter's root dir exist
  docs/nydus-fscache.md
Labels: anolis_test_pass

#584 ci: ci/release support macos arm
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: anolis_test_pass

#583 docs: add overview for data deduplication
  docs/data-deduplication.md
  docs/images/container-data-deduplication.drawio
Labels: anolis_test_pass

#593 doc: use snapshotter --fs-driver in instrunctions
  docs/nydus-fscache.md
Labels: anolis_test_pass

#591 Update nydusd doc for bootstrap creation
  docs/nydusd.md
Labels: anolis_test_pass

#596 Display detailed error in FsCacheHandler constructor when cachefiles device not ready
  src/bin/nydusd/fs_cache.rs
Labels: anolis_test_pass

#597 rafs: use real fs root ino to trigger prefetch
  rafs/src/fs.rs
Labels: anolis_test_pass

#598 Add pre built nydus v6 image
  .github/workflows/convert.yml
Labels: anolis_test_pass, anolis_test_fail

#601 storage: fix io error may let the chunk map bit always pending
  storage/src/cache/cachedfile.rs
Labels: anolis_test_pass

#605 Update dependencies
  Cargo.lock
  Cargo.toml
  api/Cargo.toml
  app/Cargo.toml
  blobfs/Cargo.toml
  blobfs/src/sync_io.rs
  deny.toml
  rafs/Cargo.toml
  rafs/src/metadata/direct_v5.rs
  rafs/src/metadata/direct_v6.rs
  src/bin/nydusd/fs_service.rs
  src/bin/nydusd/fusedev.rs
  src/bin/nydusd/virtiofs.rs
  storage/Cargo.toml
  storage/src/backend/localfs.rs
  storage/src/backend/mod.rs
  storage/src/cache/cachedfile.rs
  storage/src/cache/dummycache.rs
  storage/src/cache/mod.rs
  storage/src/cache/worker.rs
  storage/src/device.rs
  storage/src/utils.rs
  utils/Cargo.toml
Labels: anolis_test_pass

#603 Nydusify: support "view" subcommand to view Nydus image
  contrib/nydusify/cmd/nydusify.go
  contrib/nydusify/pkg/checker/rule/filesystem.go
  contrib/nydusify/pkg/checker/tool/nydusd.go
  contrib/nydusify/pkg/viewer/viewer.go
Labels: anolis_test_pass

#609 Reduce network IOs by amplifying prefetch requests
  storage/src/cache/cachedfile.rs
  storage/src/cache/worker.rs
  storage/src/meta/mod.rs
Labels: anolis_test_pass

#606 make copen always return right file size
  src/bin/nydusd/fs_cache.rs
  storage/src/factory.rs
Labels: anolis_test_pass

#611 Prefetch limit
  rafs/src/fs.rs
  rafs/src/metadata/direct_v6.rs
  rafs/src/metadata/layout/v5.rs
  rafs/src/metadata/mod.rs
  storage/src/cache/cachedfile.rs
  storage/src/cache/dummycache.rs
  storage/src/cache/worker.rs
  storage/src/device.rs
Labels: anolis_test_pass

#615 action: avoid print tons of logs
  .github/workflows/convert.yml
Labels: anolis_test_pass

#613 Dump nydusd panic info and backtrace into logger and show nydusd git commit version
  Cargo.lock
  Cargo.toml
  app/Cargo.toml
  app/src/lib.rs
  src/bin/nydusctl/commands.rs
  src/bin/nydusd/main.rs
Labels: anolis_test_pass

#610 storage: fetch blob.meta in asynchronous mode
  storage/src/cache/cachedfile.rs
  storage/src/cache/filecache/mod.rs
  storage/src/cache/fscache/mod.rs
Labels: anolis_test_pass

#620 action: enable nydus integration tests
  .github/workflows/it.yml
Labels: anolis_test_pass

#619 nydusd: gc unused blob files after umounting
  src/bin/nydusd/fs_service.rs
Labels: anolis_test_pass
