Repository dragonflyoss/nydus, pull requests merged in 2022-11, with the labels that each got.

#823 Enhance storage subsystem for coming features and fixes several bugs
  Cargo.lock
  rafs/src/fs.rs
  rafs/src/metadata/cached_v5.rs
  rafs/src/metadata/direct_v5.rs
  rafs/src/metadata/direct_v6.rs
  rafs/src/metadata/layout/v5.rs
  rafs/src/metadata/md_v5.rs
  rafs/src/metadata/md_v6.rs
  rafs/src/metadata/mod.rs
  rafs/src/mock/mock_inode.rs
  src/bin/nydus-image/builder/stargz.rs
  src/bin/nydus-image/unpack/pax.rs
  src/bin/nydusd/fs_service.rs
  storage/src/cache/cachedfile.rs
  storage/src/cache/dummycache.rs
  storage/src/cache/filecache/mod.rs
  storage/src/cache/fscache/mod.rs
  storage/src/cache/mod.rs
  storage/src/device.rs
  storage/src/factory.rs
  storage/src/meta/mod.rs
  storage/src/utils.rs
  utils/Cargo.toml
  utils/src/compress/mod.rs
  utils/src/compress/zstd_standard.rs
  utils/src/lib.rs
Labels: anolis_test_pass

#828 Backport 3 patches for stable/v2.1
  contrib/nydusify/pkg/backend/oss.go
  contrib/nydusify/pkg/packer/packer.go
  contrib/nydusify/pkg/packer/pusher.go
  contrib/nydusify/pkg/packer/pusher_test.go
Labels: anolis_test_pass

#827 improve nydus-test cases
  contrib/nydus-test/framework/distributor.py
  contrib/nydus-test/framework/utils.py
  contrib/nydus-test/functional-test/test_nydus.py
  contrib/nydus-test/functional-test/test_nydusify.py
Labels: anolis_test_pass

#826 nydusify: drop label "nydus-blob-ids" from meta layer
  contrib/nydusify/examples/manifest/manifest.json
  contrib/nydusify/pkg/cache/cache.go
  contrib/nydusify/pkg/converter/manifest.go
  contrib/nydusify/pkg/utils/constant.go
Labels: anolis_test_pass, backport/v2.1

#830 nydusify: drop label "nydus-blob-ids" from meta layer
  contrib/nydusify/examples/manifest/manifest.json
  contrib/nydusify/pkg/cache/cache.go
  contrib/nydusify/pkg/converter/manifest.go
  contrib/nydusify/pkg/utils/constant.go
Labels: anolis_testing

#829 nydus-image: fix clap
  src/bin/nydus-image/main.rs
Labels: anolis_test_pass

#800 storage: add mirror health checking support
  api/src/http.rs
  docs/nydusd.md
  storage/src/backend/connection.rs
  storage/src/backend/registry.rs
Labels: anolis_test_pass, backport/v2.1

#815 nydus-image: fix inspect to get correct path of rafs v6 file
  src/bin/nydus-image/inspect.rs
  tests/texture/image-inspect/prefetch.result
Labels: anolis_test_pass

#835 docs: add d7y doc link
  README.md
  docs/containerd-env-setup.md
  docs/nydusd.md
Labels: anolis_test_pass

#838 prepare for publishing to crates.io
  Cargo.lock
  api/Cargo.toml
  app/Cargo.toml
  blobfs/Cargo.toml
  error/Cargo.toml
  rafs/Cargo.toml
  storage/Cargo.toml
  utils/Cargo.toml
Labels: anolis_testing

#839 [backport to stable/v2.1] storage: add mirror health checking support
  api/src/http.rs
  docs/nydusd.md
  storage/src/backend/connection.rs
  storage/src/backend/registry.rs
Labels: anolis_testing

#798 Change default value of nydus-image and optimize output
  app/src/lib.rs
  contrib/nydusify/pkg/checker/tool/builder.go
  contrib/nydusify/pkg/checker/tool/inspector.go
  rafs/src/metadata/layout/v5.rs
  rafs/src/metadata/layout/v6.rs
  rafs/src/metadata/mod.rs
  src/bin/nydus-image/core/context.rs
  src/bin/nydus-image/main.rs
  tests/builder.rs
  tests/inspect.rs
Labels: anolis_test_pass

#841 storage: remove unused code for refreshing registry tokens
  storage/src/backend/registry.rs
Labels: anolis_test_pass

#842 storage: remove unused code for refreshing registry tokens
  storage/src/backend/registry.rs
Labels: anolis_test_pass

#833 Adopt zlib random access algorithm to support OCIv1 compatible nydus image
  rafs/src/fs.rs
  rafs/src/metadata/direct_v6.rs
  rafs/src/metadata/md_v5.rs
  rafs/src/metadata/md_v6.rs
  rafs/src/metadata/mod.rs
  src/bin/nydus-image/builder/stargz.rs
  src/bin/nydus-image/builder/tarball.rs
  src/bin/nydus-image/core/context.rs
  src/bin/nydus-image/core/node.rs
  src/bin/nydus-image/main.rs
  storage/src/cache/cachedfile.rs
  storage/src/cache/dummycache.rs
  storage/src/cache/filecache/mod.rs
  storage/src/cache/fscache/mod.rs
  storage/src/cache/mod.rs
  storage/src/cache/state/blob_state_map.rs
  storage/src/device.rs
  storage/src/lib.rs
  storage/src/meta/chunk_info_v1.rs
  storage/src/meta/chunk_info_v2.rs
  storage/src/meta/mod.rs
  storage/src/meta/zran.rs
  tests/smoke.rs
Labels: anolis_test_pass

#840 Reduce duplicated code by using utils/filemap
  rafs/src/lib.rs
  rafs/src/metadata/direct_v5.rs
  rafs/src/metadata/direct_v6.rs
  rafs/src/metadata/md_v6.rs
  storage/src/cache/state/indexed_chunk_map.rs
  storage/src/cache/state/persist_map.rs
  utils/src/filemap.rs
Labels: anolis_test_pass

#848 Some minor fixes
  rafs/README.md
  src/bin/nydusd/fs_service.rs
  src/bin/nydusd/main.rs
Labels: anolis_test_pass

#845 storage: correctly setup size for compressed cache file
  storage/src/cache/filecache/mod.rs
  storage/src/cache/fscache/mod.rs
Labels: anolis_test_pass

#847 Enhance RAFS v6
  rafs/src/metadata/direct_v5.rs
  rafs/src/metadata/direct_v6.rs
  rafs/src/metadata/layout/v6.rs
  rafs/src/metadata/md_v6.rs
  src/bin/nydus-image/core/bootstrap.rs
  src/bin/nydus-image/core/node.rs
Labels: anolis_test_pass

#852 builder: fix redundant blob for inline bootstrap
  src/bin/nydus-image/builder/directory.rs
  src/bin/nydus-image/builder/mod.rs
Labels: anolis_test_pass

#850 rafs: refine the way to build chunk map for v6
  rafs/src/metadata/direct_v6.rs
  rafs/src/metadata/layout/v6.rs
  src/bin/nydus-image/core/node.rs
  storage/src/cache/filecache/mod.rs
Labels: anolis_test_pass

#849 rafs: fix a bug in set prefetch table size of empty filesysetem
  src/bin/nydus-image/core/bootstrap.rs
Labels: anolis_test_pass, backport/v2.1

#844 Refine nydus-image/nydusd commandline options
  src/bin/nydus-image/main.rs
  src/bin/nydusd/main.rs
Labels: anolis_test_pass

#853 nydus-test: don't test nydus-image for localfs backend
  contrib/nydus-test/functional-test/test_nydus.py
Labels: anolis_test_pass

#854 Enhance pseudo fs e2e test and refine nydusd client error message
  contrib/nydus-test/functional-test/test_api.py
  contrib/nydus-test/functional-test/test_nydus.py
  contrib/nydus-test/nydusd_client.py
Labels: anolis_test_pass

#857 README.md: mark buildkit integration as completed
  README.md
Labels: anolis_testing

#861 test: fix invalid digest value of repeatable blob
  tests/nydusd.rs
  tests/texture/repeatable/blake3-lz4_block-non_repeatable
  tests/texture/repeatable/sha256-nocompress-repeatable
Labels: anolis_test_pass

#862 storage: treat cache files as uncompressed when the algorithm is None
  storage/src/cache/filecache/mod.rs
Labels: anolis_test_pass

#863 nydusify: fix the concurrency error when push image blob layer to oss backend
  contrib/nydusify/pkg/backend/oss.go
Labels: anolis_test_pass

#865 nydus-image: keep compatibility with "nydus-image check --bootstrap"
  contrib/nydusify/pkg/checker/tool/builder.go
  src/bin/nydus-image/main.rs
Labels: anolis_test_pass

#866 nydusify: beautify version print message of nydusify
  contrib/nydusify/Makefile
  contrib/nydusify/cmd/nydusify.go
Labels: anolis_testing, backport/v2.1

#869 storage: fix registry to avoid print bearer auth
  storage/src/backend/registry.rs
Labels: anolis_testing

#864 nydus-image: prevent inconsistent RAFS version/compressor/digester of parent bootstrap/chunk dict
  rafs/src/metadata/mod.rs
  src/bin/nydus-image/core/blob_compact.rs
  src/bin/nydus-image/core/bootstrap.rs
  src/bin/nydus-image/core/chunk_dict.rs
  src/bin/nydus-image/main.rs
  src/bin/nydus-image/merge.rs
Labels: anolis_testing

#875 nydusify: fix a typo in its version message
  contrib/nydusify/Makefile
  contrib/nydusify/cmd/nydusify.go
Labels: anolis_test_pass

#876 cargo: update version of dbs-uhttp
  Cargo.lock
Labels: anolis_test_pass

#872 nydusify: beautify version print message of nydusify
  contrib/nydusify/Makefile
  contrib/nydusify/cmd/nydusify.go
Labels: anolis_testing

#877 cargo: update version of dbs-uhttp
  Cargo.lock
Labels: anolis_test_pass

#881 nydusify: change default fs version to 6
  contrib/nydusify/cmd/nydusify.go
Labels: anolis_test_pass

#880 fix too frequent retry
  storage/src/cache/cachedfile.rs
  storage/src/cache/worker.rs
Labels: bug, anolis_test_pass

#883 storage: user unstable sort to reduce memory allocation
  storage/src/cache/cachedfile.rs
Labels: anolis_test_pass

#888 nydusd: fix fscache prefetch threads can't exit in shared domain mode
  src/bin/nydusd/blob_cache.rs
  src/bin/nydusd/fs_cache.rs
  storage/src/cache/fscache/mod.rs
  storage/src/device.rs
  storage/src/factory.rs
Labels: anolis_test_pass

#882 Fix frequent retry
  storage/src/cache/cachedfile.rs
  storage/src/cache/worker.rs
Labels: anolis_test_pass

#895 actions: remove unused var
  .github/workflows/release.yml
Labels: anolis_testing

#860 Introduce Nydus configuration file format version 2
  Cargo.lock
  api/Cargo.toml
  api/src/config.rs
  api/src/http.rs
  api/src/http_endpoint_v2.rs
  api/src/lib.rs
  blobfs/Cargo.toml
  blobfs/src/lib.rs
  docs/samples/blob_cache_entry_configuration_v2.toml
  docs/samples/configuration_v2.toml
  rafs/src/fs.rs
  rafs/src/metadata/md_v5.rs
  rafs/src/metadata/mod.rs
  src/bin/nydus-image/main.rs
  src/bin/nydus-image/unpack/mod.rs
  src/bin/nydusctl/commands.rs
  src/bin/nydusd/blob_cache.rs
  src/bin/nydusd/fs_cache.rs
  src/bin/nydusd/fs_service.rs
  src/lib.rs
  storage/Cargo.toml
  storage/src/backend/connection.rs
  storage/src/backend/localfs.rs
  storage/src/backend/oss.rs
  storage/src/backend/registry.rs
  storage/src/cache/cachedfile.rs
  storage/src/cache/dummycache.rs
  storage/src/cache/filecache/mod.rs
  storage/src/cache/fscache/mod.rs
  storage/src/cache/worker.rs
  storage/src/device.rs
  storage/src/factory.rs
  storage/src/lib.rs
Labels: anolis_testing

#898 2.1 port nydusify
  contrib/nydusify/cmd/nydusify.go
  contrib/nydusify/pkg/build/builder.go
  contrib/nydusify/pkg/build/workflow.go
  contrib/nydusify/pkg/converter/converter.go
Labels: anolis_testing

#887 rafs: prefetch based on blob chunks rather than files
  rafs/src/fs.rs
  rafs/src/metadata/md_v6.rs
  rafs/src/metadata/mod.rs
Labels: anolis_testing

#904 builder: use chunk v1 for native directory build
  src/bin/nydus-image/main.rs
Labels: anolis_testing

#905 nydusd: allow to get fusedev fsservice from fusedev daemon
  src/bin/nydusd/fs_service.rs
  src/bin/nydusd/fusedev.rs
  src/bin/nydusd/virtiofs.rs
Labels: anolis_testing

#908 utils: fix a warning generated when decoding chunk data
  storage/src/cache/cachedfile.rs
Labels: anolis_test_pass

#892 2.1 prefetch metrics
  storage/src/cache/worker.rs
  utils/src/metrics.rs
Labels: anolis_test_pass

#899 Let nydusd show prefetch bandwidth and latency
  src/bin/nydusctl/commands.rs
  storage/src/cache/worker.rs
Labels: anolis_testing

#909 storage: enhance retryable registry http scheme
  docs/containerd-env-setup.md
  storage/src/backend/registry.rs
Labels: anolis_test_pass
