Repository dragonflyoss/nydus, pull requests merged in 2022-10, with the labels that each got.

#766 storage: reduce dependence crates
  Cargo.lock
  deny.toml
  rafs/Cargo.toml
  storage/Cargo.toml
  storage/src/backend/oss.rs
  storage/src/cache/worker.rs
  storage/src/lib.rs
Labels: anolis_test_pass

#770 util: add FileMapState to map a file region into current process
  utils/src/filemap.rs
  utils/src/lib.rs
  utils/src/mpmc.rs
Labels: anolis_test_pass

#771 rafs: refine doc and consts
  rafs/src/fs.rs
  rafs/src/metadata/cached_v5.rs
  rafs/src/metadata/direct_v5.rs
  rafs/src/metadata/direct_v6.rs
  rafs/src/metadata/layout/v5.rs
  rafs/src/metadata/layout/v6.rs
  rafs/src/metadata/md_v5.rs
  rafs/src/metadata/mod.rs
  rafs/src/mock/mock_inode.rs
  src/bin/nydus-image/inspect.rs
Labels: anolis_test_pass

#773 api: reduce dependencies when used by client
  Cargo.lock
  Cargo.toml
  api/Cargo.toml
  api/src/http.rs
  api/src/http_endpoint_common.rs
  api/src/http_endpoint_v1.rs
  api/src/http_endpoint_v2.rs
  api/src/http_handler.rs
  api/src/lib.rs
  error/src/error.rs
  src/bin/nydusd/api_server_glue.rs
  utils/src/metrics.rs
Labels: anolis_test_pass

#774 Split `RafsInode` into `RafsInode` and `RafsInodeExt`
  rafs/src/fs.rs
  rafs/src/lib.rs
  rafs/src/metadata/cached_v5.rs
  rafs/src/metadata/direct_v5.rs
  rafs/src/metadata/direct_v6.rs
  rafs/src/metadata/layout/mod.rs
  rafs/src/metadata/layout/v5.rs
  rafs/src/metadata/md_v5.rs
  rafs/src/metadata/mod.rs
  rafs/src/metadata/noop.rs
  rafs/src/mock/mock_chunk.rs
  rafs/src/mock/mock_inode.rs
  rafs/src/mock/mock_super.rs
  src/bin/nydus-image/core/bootstrap.rs
  src/bin/nydus-image/core/node.rs
  src/bin/nydus-image/core/tree.rs
  src/bin/nydus-image/inspect.rs
  src/bin/nydus-image/merge.rs
  src/bin/nydus-image/unpack/mod.rs
  src/bin/nydus-image/unpack/pax.rs
  src/bin/nydus-image/unpack/pax/test.rs
  src/bin/nydusd/fusedev.rs
  storage/src/cache/state/blob_state_map.rs
  storage/src/device.rs
  storage/src/meta/mod.rs
  storage/src/test.rs
  tests/builder.rs
  utils/src/compress/mod.rs
  utils/src/digest.rs
Labels: anolis_testing

#775 Refine nydus-image: part 1
  rafs/src/fs.rs
  rafs/src/metadata/chunk.rs
  rafs/src/metadata/inode.rs
  rafs/src/metadata/layout/mod.rs
  rafs/src/metadata/layout/v5.rs
  rafs/src/metadata/layout/v6.rs
  rafs/src/metadata/mod.rs
  src/bin/nydus-image/builder/mod.rs
  src/bin/nydus-image/builder/stargz.rs
  src/bin/nydus-image/core/blob.rs
  src/bin/nydus-image/core/blob_compact.rs
  src/bin/nydus-image/core/bootstrap.rs
  src/bin/nydus-image/core/chunk_dict.rs
  src/bin/nydus-image/core/context.rs
  src/bin/nydus-image/core/layout.rs
  src/bin/nydus-image/core/node.rs
  src/bin/nydus-image/core/prefetch.rs
  src/bin/nydus-image/core/tree.rs
  src/bin/nydus-image/inspect.rs
  src/bin/nydus-image/main.rs
  src/bin/nydus-image/merge.rs
  src/bin/nydus-image/unpack/mod.rs
  src/bin/nydus-image/unpack/pax.rs
  storage/src/device.rs
Labels: anolis_test_fail

#782 rafs: fix bug in handling extended attributes
  rafs/src/metadata/cached_v5.rs
  rafs/src/metadata/layout/mod.rs
  rafs/src/metadata/layout/v5.rs
  rafs/src/metadata/layout/v6.rs
  src/bin/nydus-image/builder/stargz.rs
Labels: anolis_test_fail

#783 README.md: add OSSEU22 meterials
  README.md
Labels: anolis_test_pass

#780 refact: use specified object prefix and meta prefix directly
  contrib/nydusify/pkg/backend/oss.go
  contrib/nydusify/pkg/packer/packer.go
  contrib/nydusify/pkg/packer/pusher.go
  contrib/nydusify/pkg/packer/pusher_test.go
Labels: anolis_test_pass

#787 nydusd: enlarge default fuse server threads
  src/bin/nydusd/main.rs
Labels: anolis_test_pass, backport/v2.1

#772 rafs: enforce stricter inode validation rules for v5
  rafs/src/metadata/cached_v5.rs
  rafs/src/metadata/direct_v5.rs
Labels: anolis_test_pass

#735 release: update version on build automatically
  Cargo.lock
  Cargo.toml
  app/README.md
  app/build.rs
  app/src/lib.rs
  src/bin/nydus-image/main.rs
  src/bin/nydusctl/main.rs
  src/bin/nydusd/main.rs
Labels: anolis_testing

#788 storage: retry timeout chunks for fscache ondemand path
  storage/src/cache/cachedfile.rs
Labels: anolis_test_pass, backport/v2.1

#791 nydusify: fix overlay error for image with single layer
  contrib/nydusify/pkg/checker/rule/filesystem.go
  contrib/nydusify/pkg/checker/tool/image.go
Labels: anolis_test_pass, backport/v2.1

#793 nydus-image/v5: prefetch table should contain inode numbers rather its index
  src/bin/nydus-image/core/bootstrap.rs
  src/bin/nydus-image/core/prefetch.rs
Labels: anolis_test_pass

#794 nydus-image/v5: prefetch table should contain inode numbers rather it…
  src/bin/nydus-image/core/bootstrap.rs
  src/bin/nydus-image/core/prefetch.rs
Labels: anolis_test_pass

#778 Second part to refine nydus-image
  rafs/src/lib.rs
  src/bin/nydus-image/builder/directory.rs
  src/bin/nydus-image/builder/stargz.rs
  src/bin/nydus-image/core/blob.rs
  src/bin/nydus-image/core/blob_compact.rs
  src/bin/nydus-image/core/bootstrap.rs
  src/bin/nydus-image/core/context.rs
  src/bin/nydus-image/core/prefetch.rs
  src/bin/nydus-image/main.rs
  src/bin/nydus-image/merge.rs
  src/bin/nydus-image/stat.rs
  src/bin/nydus-image/validator.rs
  storage/src/cache/worker.rs
  utils/src/digest.rs
Labels: anolis_test_pass

#785 nydus-image: fix inspect to get correct path of rafs v6 file
  src/bin/nydus-image/inspect.rs
Labels: anolis_test_pass

#792 Improve implementation to convert stargz TOC into RAFS fs
  rafs/src/metadata/inode.rs
  rafs/src/metadata/layout/v5.rs
  src/bin/nydus-image/builder/stargz.rs
  src/bin/nydus-image/core/node.rs
  src/bin/nydus-image/main.rs
  src/bin/nydus-image/unpack/pax/test.rs
  storage/src/lib.rs
  storage/src/meta/mod.rs
  tests/builder.rs
Labels: anolis_test_pass

#790 fix mirror's performance issue
  api/src/http.rs
  docs/nydusd.md
  storage/src/backend/connection.rs
  storage/src/backend/oss.rs
  storage/src/backend/registry.rs
Labels: anolis_test_pass, backport/v2.1

#799 Backport some patches for stable/v2.1
  api/src/http.rs
  contrib/nydusify/pkg/checker/rule/filesystem.go
  contrib/nydusify/pkg/checker/tool/image.go
  docs/nydusd.md
  storage/src/backend/connection.rs
  storage/src/backend/oss.rs
  storage/src/backend/registry.rs
  storage/src/cache/cachedfile.rs
Labels: anolis_test_pass

#802 nydusd: simplify the way to use localfs for fuse subcommand
  src/bin/nydusd/main.rs
  storage/src/cache/filecache/mod.rs
Labels: anolis_test_pass

#804 release: update version on build automatically
  Cargo.lock
  Cargo.toml
  app/README.md
  app/build.rs
  app/src/lib.rs
  src/bin/nydus-image/main.rs
  src/bin/nydusctl/main.rs
  src/bin/nydusd/main.rs
Labels: anolis_testing

#805 action/nydus-test: stop on the first test failure
  .github/workflows/it.yml
Labels: anolis_test_pass

#806 action/nydus-test: stop on the first test failure
  .github/workflows/it.yml
Labels: anolis_test_pass

#808 chore: ci action adds paths-ignore
  .github/workflows/ci.yml
Labels: enhancement, anolis_test_pass

#809 action: update release notes for download mirror
  .github/workflows/release.yml
Labels: anolis_test_pass

#795 Enhance nydus-image to generate RAFS filesystem directly from tarball
  rafs/src/metadata/layout/v5.rs
  rafs/src/metadata/layout/v6.rs
  src/bin/nydus-image/builder/directory.rs
  src/bin/nydus-image/builder/mod.rs
  src/bin/nydus-image/builder/stargz.rs
  src/bin/nydus-image/builder/tarball.rs
  src/bin/nydus-image/core/blob.rs
  src/bin/nydus-image/core/blob_compact.rs
  src/bin/nydus-image/core/bootstrap.rs
  src/bin/nydus-image/core/context.rs
  src/bin/nydus-image/core/node.rs
  src/bin/nydus-image/core/tree.rs
  src/bin/nydus-image/main.rs
  tests/texture/stargz/alpine-stargz.index.json
  tests/texture/stargz/alpine-stargz.tar.gz
  tests/texture/tar/all-entry-type-macos.tar
  tests/texture/tar/all-entry-type.tar
  tests/texture/tar/empty.tar
Labels: anolis_test_pass

#796 Introduce blob meta format v2
  rafs/src/metadata/chunk.rs
  rafs/src/metadata/layout/v6.rs
  src/bin/nydus-image/builder/stargz.rs
  src/bin/nydus-image/core/blob.rs
  src/bin/nydus-image/core/blob_compact.rs
  src/bin/nydus-image/core/context.rs
  src/bin/nydus-image/core/node.rs
  storage/src/meta/chunk_info_v1.rs
  storage/src/meta/chunk_info_v2.rs
  storage/src/meta/mod.rs
  utils/src/filemap.rs
Labels: anolis_test_pass

#813 optimize prefetch table for workload
  Cargo.lock
  Cargo.toml
  rafs/src/metadata/layout/v5.rs
  rafs/src/metadata/layout/v6.rs
  src/bin/nydus-image/core/prefetch.rs
Labels: anolis_test_pass

#818 nydus-image: fix prefetch table size for rafs v6
  src/bin/nydus-image/core/bootstrap.rs
Labels: anolis_test_pass

#816 Refine storage device abstraction and implementation
  Cargo.lock
  rafs/src/metadata/chunk.rs
  rafs/src/metadata/inode.rs
  rafs/src/metadata/layout/v6.rs
  src/bin/nydus-image/builder/mod.rs
  src/bin/nydus-image/builder/stargz.rs
  src/bin/nydus-image/builder/tarball.rs
  src/bin/nydus-image/core/blob.rs
  src/bin/nydus-image/core/blob_compact.rs
  src/bin/nydus-image/core/context.rs
  src/bin/nydus-image/core/node.rs
  src/bin/nydus-image/main.rs
  src/bin/nydusd/fusedev.rs
  storage/Cargo.toml
  storage/src/cache/mod.rs
  storage/src/device.rs
  storage/src/meta/chunk_info_v1.rs
  storage/src/meta/chunk_info_v2.rs
  storage/src/meta/mod.rs
  storage/src/meta/zran.rs
  tests/texture/zran/233c72f2b6b698c07021c4da367cfe2dff4f049efbaa885ca0ff760ea297865a.blob.meta
  utils/src/compress/zlib_random.rs
Labels: anolis_test_pass

#822 upgrade clap to 4.0
  Cargo.lock
  Cargo.toml
  src/bin/nydus-image/main.rs
  src/bin/nydusctl/main.rs
  src/bin/nydusd/main.rs
  src/bin/nydusd/service_controller.rs
  src/bin/nydusd/upgrade.rs
Labels: anolis_test_pass

#820 docs: update nerdctl description
  README.md
  docs/containerd-env-setup.md
Labels: anolis_testing

#824 fixup! Upgrade clap to 4.0
  src/bin/nydusd/main.rs
Labels: anolis_test_pass
