Repository dragonflyoss/nydus, pull requests merged in 2023-02, with the labels that each got.

#1045 Fixes two bugs related to ZRan and fscache
  api/src/config.rs
  rafs/src/metadata/mod.rs
  storage/src/meta/mod.rs
Labels: anolis_test_pass

#1043 action: convert and check top images for zran
  .github/workflows/convert.yml
  .github/workflows/integration.yml
  .github/workflows/release.yml
  .github/workflows/smoke.yml
Labels: anolis_test_pass

#1046 action: fix referenced oci image for zran
  .github/workflows/convert.yml
Labels: anolis_test_pass

#1048 action: enable fsck.erofs for ZRan images
  .github/workflows/convert.yml
Labels: anolis_test_pass

#1049 action: download fsck.erofs before using
  .github/workflows/convert.yml
Labels: anolis_test_pass

#1047 smoke: migrate api tests from contrib/nydus-test
  smoke/tests/api_test.go
  smoke/tests/tool/nydusd.go
Labels: anolis_test_pass

#1050 add e2e testcases for ci
  tests/bats/Makefile
  tests/bats/build_docker_image.bats
  tests/bats/common_tests.sh
  tests/bats/compile_ctr_remote.bats
  tests/bats/compile_nydus_snapshotter.bats
  tests/bats/compile_nydusd.bats
  tests/bats/install_bats.sh
  tests/bats/run_container_with_rafs.bats
  tests/bats/run_container_with_zran.bats
Labels: anolis_test_pass

#1052 Fix anolis test
  docs/nydus-fscache.md
  misc/example/containerd-entrypoint.sh
  tests/bats/common_tests.sh
Labels: anolis_test_fail

#1053 smoke: support async test cases
  smoke/tests/api_test.go
  smoke/tests/compatibility_test.go
  smoke/tests/image_test.go
  smoke/tests/native_layer_test.go
  smoke/tests/tool/iterator.go
  smoke/tests/tool/test/suite.go
  smoke/tests/zran_layer_test.go
Labels: anolis_test_fail

#974 storage: add new backend `HttpProxy`
  Cargo.lock
  Cargo.toml
  api/src/config.rs
  blobfs/Cargo.toml
  clib/Cargo.toml
  docs/nydusd.md
  rafs/Cargo.toml
  storage/Cargo.toml
  storage/src/backend/connection.rs
  storage/src/backend/http_proxy.rs
  storage/src/backend/mod.rs
  storage/src/factory.rs
  storage/src/meta/toc.rs
Labels: anolis_test_fail

#1058 add e2e testcases for ci for stable branch
  tests/bats/Makefile
  tests/bats/build_docker_image.bats
  tests/bats/common_tests.sh
  tests/bats/compile_ctr_remote.bats
  tests/bats/compile_nydus_snapshotter.bats
  tests/bats/compile_nydusd.bats
  tests/bats/install_bats.sh
  tests/bats/run_container_with_rafs.bats
  tests/bats/run_container_with_zran.bats
Labels: anolis_test_pass

#1059 nydus-test: fix debug panic
  contrib/nydus-test/framework/workload_gen.py
Labels: anolis_test_pass

#1063 cargo: Update dependencies to resolve security vulnerabilities
  Cargo.lock
Labels: anolis_test_pass

#972 storage: introduce new backend localdisk in nydusd
  Cargo.lock
  Cargo.toml
  api/src/config.rs
  blobfs/Cargo.toml
  clib/Cargo.toml
  docs/nydusd.md
  rafs/Cargo.toml
  storage/Cargo.toml
  storage/README.md
  storage/src/backend/localdisk.rs
  storage/src/backend/mod.rs
  storage/src/factory.rs
  storage/src/meta/toc.rs
Labels: anolis_test_pass

#1062 zran: fix an assert when generating ZRAN images
  src/bin/nydus-image/builder/tarball.rs
  utils/src/compress/zlib_random.rs
Labels: anolis_test_pass

#1068 nydusify: Fix nydusify help messages
  contrib/nydusify/cmd/nydusify.go
Labels: anolis_test_fail

#1067 nydusify: fix overlayfs mount options for check
  contrib/nydusify/pkg/checker/rule/filesystem.go
  contrib/nydusify/pkg/checker/tool/image.go
Labels: anolis_test_pass

#1069 storage: fix bugs in prefetch data for ZRan images
  storage/src/cache/cachedfile.rs
  storage/src/cache/worker.rs
  storage/src/device.rs
  storage/src/meta/mod.rs
Labels: anolis_test_fail

#1070 dep: remove dependency on ansi-term
  Cargo.lock
  app/Cargo.toml
  app/src/lib.rs
Labels: anolis_test_pass

#1071 storage: fix a out of range bug related to zran
  storage/src/meta/mod.rs
Labels: anolis_test_pass

#1072 nydus-service: split service framework from nydus into nydus-service
  Cargo.lock
  Cargo.toml
  api/src/lib.rs
  app/src/lib.rs
  blobfs/Cargo.toml
  clib/Cargo.toml
  rafs/Cargo.toml
  service/Cargo.toml
  service/src/blob_cache.rs
  service/src/daemon.rs
  service/src/fs_cache.rs
  service/src/fs_service.rs
  service/src/fusedev.rs
  service/src/lib.rs
  service/src/singleton.rs
  service/src/upgrade.rs
  src/bin/nydus-image/main.rs
  src/bin/nydusctl/main.rs
  src/bin/nydusd/main.rs
  src/bin/nydusd/virtiofs.rs
  src/lib.rs
Labels: anolis_test_pass

#1075 builder: fix configuration error on chunk dict load
  src/bin/nydus-image/main.rs
Labels: anolis_test_pass

#1074 service: move DaemonController from nydus into nydus-service
  service/src/daemon.rs
  src/bin/nydusd/api_server_glue.rs
  src/bin/nydusd/main.rs
Labels: anolis_test_pass

#1076 ctr-remote: update dependencies to latest
  contrib/ctr-remote/go.mod
  contrib/ctr-remote/go.sum
Labels: anolis_test_pass

#1079 rafs: reserve bits in RafsSuperFlags for future compatible changes
  Cargo.lock
  rafs/src/metadata/mod.rs
Labels: anolis_test_pass

#1073 nydusify: speed up conversion with tar2rafs
  contrib/nydusify/go.mod
  contrib/nydusify/go.sum
  smoke/go.mod
  smoke/go.sum
Labels: anolis_test_pass

#1083 nydusify: upgrade deps to fix lost prefetch table
  contrib/nydusify/go.mod
  contrib/nydusify/go.sum
  smoke/go.mod
  smoke/go.sum
Labels: anolis_test_pass

#1086 Bugfix for `BackendConfigV2` deserialization
  api/src/config.rs
Labels: anolis_test_pass

#1085 builder: fix inode xattr flag for tar2rafs build
  src/bin/nydus-image/builder/tarball.rs
Labels: anolis_test_pass

#1084 smoke: make test log clearer
  .github/workflows/smoke.yml
  smoke/tests/image_test.go
  smoke/tests/tool/util.go
Labels: anolis_test_pass

#1087 smoke: fix possible image name conflicts
  smoke/go.mod
  smoke/go.sum
  smoke/tests/image_test.go
Labels: anolis_test_pass

#1088 service: fix a bug to correct shutdown service manager
  service/src/daemon.rs
Labels: anolis_testing

#1095 rafs: reserve bits in RafsSuperFlags to be compatible with v2.2
  rafs/src/metadata/mod.rs
Labels: anolis_test_pass

#1082 nydus-image: add `backend-config` support to `nydus-image unpack`
  src/bin/nydus-image/main.rs
  src/bin/nydus-image/unpack/mod.rs
Labels: anolis_test_pass

#1096 builder: fix invalid compressed offset in image.blob toc entry
  src/bin/nydus-image/core/blob.rs
  src/bin/nydus-image/core/blob_compact.rs
  src/bin/nydus-image/core/context.rs
  src/bin/nydus-image/core/node.rs
Labels: anolis_test_pass

#1100 Revert "storage: return Ok(None) for check_range_ready_and_mark_pendi…
  storage/src/cache/state/blob_state_map.rs
Labels: anolis_test_pass

#1101 service: improve the resuability of create_daemon
  service/src/singleton.rs
  src/bin/nydusd/main.rs
Labels: anolis_test_pass

#1103 nydusify: pack: add missing cli parameters
  contrib/nydusify/cmd/nydusify.go
  contrib/nydusify/pkg/packer/packer.go
Labels: anolis_test_pass

#1104 rafs: enforce stricter and safer validation of RAFS v6 images
  rafs/src/metadata/direct_v6.rs
Labels: anolis_test_pass

#1105 publish: update crate version for nydus 2.2 rc3
  Cargo.lock
  Cargo.toml
  clib/Cargo.toml
  rafs/Cargo.toml
  service/Cargo.toml
  storage/Cargo.toml
Labels: anolis_test_pass

#1106 rafs: fix a bug in calculate offset for dirent name
  rafs/src/metadata/direct_v6.rs
Labels: anolis_testing, backport/v2.1

#1107 service: fix a unused variable warning on macos
  service/src/singleton.rs
Labels: anolis_test_pass

#1109 add a new test case: run_container_with_rafs_and_compile_linux.bats
  tests/bats/Makefile
  tests/bats/run_container_with_rafs_and_compile_linux.bats
Labels: anolis_test_pass

#1108 Correctly generate mapped-blkaddr for RAFS devslot array
  api/src/config.rs
  src/bin/nydus-image/core/bootstrap.rs
Labels: anolis_test_pass

#1115 action: convert arm images in top image test
  .github/workflows/convert.yml
Labels: anolis_test_pass

#1118 nydusd: remove deprecate params
  api/src/http_handler.rs
  src/bin/nydusd/api_server_glue.rs
Labels: anolis_test_pass
