Repository dragonflyoss/nydus, pull requests merged in 2023-07, with the labels that each got.

#1331 nydusify: bump github.com/goharbor/acceleration-service v0.2.5
  contrib/nydusify/go.mod
  contrib/nydusify/go.sum
Labels: anolis_test_pass

#1343 docs: update the OpenAnolis kernel installation guide in fscache doc.
  docs/nydus-fscache.md
Labels: anolis_test_pass

#1347 fix: merge io from same blob panic
  storage/src/device.rs
Labels: anolis_test_pass

#1350 action: reduce the number of times the codecov tool sends comments
  .github/codecov.yml
Labels: anolis_testing

#1353 docs: add containerd runtime-level snapshotter usage for nydus
  docs/containerd-env-setup.md
Labels: anolis_testing

#1360 fix incidental bugs in ci test
  tests/bats/Makefile
  tests/bats/common_tests.sh
Labels: anolis_test_pass

#1358 fix incidental bugs in ci test
  tests/bats/Makefile
  tests/bats/common_tests.sh
Labels: anolis_test_pass

#1354 nydus-image: add unit test for setting default compression algorithm
  builder/src/core/blob.rs
Labels: anolis_test_pass

#1348 fix: large files broke prefetch
  rafs/src/fs.rs
  smoke/tests/api_test.go
  smoke/tests/texture/layer.go
  smoke/tests/tool/layer.go
  storage/src/cache/worker.rs
  storage/src/device.rs
Labels: anolis_test_pass, backport/v2.2

#1311 fix: amplify io is too large to hold in fuse buffer
  Cargo.toml
  rafs/src/fs.rs
  smoke/Makefile
  smoke/tests/api_test.go
  smoke/tests/image_test.go
  smoke/tests/native_layer_test.go
  smoke/tests/tool/context.go
  smoke/tests/tool/iterator.go
  smoke/tests/tool/nydusd.go
  smoke/tests/tool/verify.go
Labels: anolis_test_pass, backport/v2.2

#1369 Makefile: allow to build debug version nydusd
  Makefile
Labels: anolis_test_pass

#1371 change a new nydus image for ci test
  tests/bats/run_container_with_rafs_and_compile_linux.bats
Labels: anolis_test_pass

#1370 change a new nydus image for ci test
  tests/bats/run_container_with_rafs_and_compile_linux.bats
Labels: anolis_test_pass

#1372 [backport] rafs: avoid a debug_assert related to v5 amplify io
  rafs/src/metadata/md_v5.rs
Labels: anolis_test_pass

#1374 nydus-image: add unit test for setting default compression algorithm
  src/bin/nydus-image/core/blob.rs
Labels: anolis_test_pass

#1382 parse image pull auth from env
  api/src/config.rs
  docs/nydusd.md
  src/bin/nydusd/main.rs
Labels: anolis_test_pass

#1376 builder: optimize tarfs building speed by skipping file content
  builder/src/tarball.rs
  utils/src/reader.rs
Labels: anolis_test_pass
