Repository dragonflyoss/nydus, pull requests merged in 2023-01, with the labels that each got.

#984 fscache: fix a bug introduced by commit eac959f
  storage/src/cache/cachedfile.rs
Labels: anolis_test_pass

#980 storage: update documentation for blob meta to reflect recent changes
  rafs/src/metadata/layout/v6.rs
  src/bin/nydus-image/builder/mod.rs
  src/bin/nydus-image/core/blob.rs
  src/bin/nydus-image/core/context.rs
  storage/src/cache/cachedfile.rs
  storage/src/cache/mod.rs
  storage/src/meta/chunk_info_v1.rs
  storage/src/meta/chunk_info_v2.rs
  storage/src/meta/mod.rs
  storage/src/meta/toc.rs
  storage/src/meta/zran.rs
Labels: anolis_test_pass

#986 ci: disable build cache for top images test
  .github/workflows/convert.yml
Labels: anolis_testing

#985 Fix warning message related to data prefetch
  rafs/src/fs.rs
  src/bin/nydus-image/core/context.rs
  src/bin/nydus-image/inspect.rs
  src/bin/nydus-image/main.rs
  src/bin/nydusd/fs_cache.rs
  storage/src/cache/filecache/mod.rs
  storage/src/device.rs
  storage/src/meta/mod.rs
Labels: anolis_testing

#988 docs: update nydus path to /usr/bin for better compatibility
  Makefile
  docs/containerd-env-setup.md
  docs/nydus-fscache.md
  docs/nydus-zran.md
Labels: anolis_test_pass

#989 cross: install cmake
  Cross.toml
Labels: anolis_test_pass

#992 storage: introduce BlobFeatures::SEPARATE to support tar-ref
  rafs/src/metadata/layout/v6.rs
  src/bin/nydus-image/builder/mod.rs
  src/bin/nydus-image/builder/tarball.rs
  src/bin/nydus-image/core/blob.rs
  src/bin/nydus-image/core/context.rs
  src/bin/nydus-image/core/node.rs
  src/bin/nydus-image/inspect.rs
  src/bin/nydus-image/main.rs
  src/bin/nydus-image/merge.rs
  storage/src/cache/filecache/mod.rs
  storage/src/cache/fscache/mod.rs
  storage/src/device.rs
  storage/src/meta/chunk_info_v2.rs
  storage/src/meta/mod.rs
Labels: anolis_test_pass

#993 CVE-2007-4559 Patch
  contrib/nydus-test/framework/utils.py
Labels: anolis_test_pass

#994 nydus-image: fix a bug in handle xattr for tarballs
  src/bin/nydus-image/builder/tarball.rs
  storage/src/cache/filecache/mod.rs
  storage/src/cache/fscache/mod.rs
Labels: anolis_test_pass

#995 Enhance the way to handle `--bootstrap` option for nydus-image
  api/src/config.rs
  rafs/src/fs.rs
  rafs/src/metadata/mod.rs
  src/bin/nydus-image/core/bootstrap.rs
  src/bin/nydus-image/core/chunk_dict.rs
  src/bin/nydus-image/core/context.rs
  src/bin/nydus-image/inspect.rs
  src/bin/nydus-image/main.rs
  src/bin/nydus-image/merge.rs
  src/bin/nydus-image/stat.rs
  src/bin/nydus-image/unpack/mod.rs
  src/bin/nydus-image/validator.rs
  src/blob_cache.rs
Labels: anolis_test_pass

#996 nydus-image: refine image to enable page cache sharing for EROFS
  rafs/src/metadata/layout/v6.rs
  src/bin/nydus-image/core/node.rs
Labels: anolis_test_pass

#987 read prefetch list(runtime) from file
  api/openapi/nydus-api-v1.yaml
  contrib/nydus-test/framework/rafs.py
  contrib/nydus-test/functional-test/test_nydus.py
  contrib/nydus-test/functional-test/test_nydusify.py
  contrib/nydus-test/functional-test/test_stress.py
  src/bin/nydusd/main.rs
Labels: anolis_test_pass

#997 utils: fix a compilation error for libz-ng-sys on ppc64le
  Cargo.lock
  utils/Cargo.toml
  utils/src/compress/zlib_random.rs
Labels: anolis_test_pass

#999 utils: use `powerpc64` instead of `ppc64le`
  Cargo.lock
  Cargo.toml
  utils/Cargo.toml
Labels: anolis_test_pass

#982 Refine nydusd/fscache implementation
  src/bin/nydusd/main.rs
  src/bin/nydusd/service_controller.rs
  src/fs_cache.rs
  src/lib.rs
Labels: anolis_test_pass

#1000 rustup: upgrade toolchain to 1.66.1 and fix cargo clippy warnings
  Cargo.lock
  Makefile
  app/build.rs
  blobfs/src/sync_io.rs
  misc/musl-static/Dockerfile
  misc/nydus-smoke/Dockerfile
  rafs/src/metadata/layout/v6.rs
  rafs/src/metadata/mod.rs
  rust-toolchain
  src/bin/nydus-image/builder/directory.rs
  src/bin/nydus-image/builder/stargz.rs
  src/bin/nydus-image/builder/tarball.rs
  src/bin/nydus-image/core/blob_compact.rs
  src/bin/nydus-image/core/bootstrap.rs
  src/bin/nydus-image/core/context.rs
  src/bin/nydus-image/inspect.rs
  storage/src/backend/s3.rs
  storage/src/device.rs
  utils/src/compress/mod.rs
Labels: anolis_test_fail

#1001 dep: update fuse-backend to fix a bug in lookup()
  Cargo.lock
  Cargo.toml
Labels: anolis_test_pass

#1002 storage: correctly calculate compressed blob size for RAFS v5
  src/bin/nydus-image/main.rs
  storage/src/device.rs
Labels: anolis_test_fail

#1003 storage: add BlobFeature::HAS_TAR_HEADER to calcalute
  src/bin/nydus-image/core/context.rs
  storage/src/device.rs
  storage/src/meta/mod.rs
Labels: anolis_test_fail

#1005 utils: tweek Cargo.toml for powerpc64le again
  utils/Cargo.toml
Labels: anolis_test_fail

#1004 storage: do not generate digest mismatch messages for old images
  storage/src/cache/mod.rs
Labels: anolis_test_fail

#1008 docs: add some badges in README.md
  README.md
Labels: anolis_test_fail

#1009 chore: add CODEOWNERS to .github
  .github/CODEOWNERS
  .gitignore
Labels: enhancement, anolis_test_fail

#1013 utils: let flate2 use libz instead of libz-ng for ppc64le
  Cargo.lock
  utils/Cargo.toml
  utils/src/compress/zlib_random.rs
Labels: anolis_test_fail

#1012 nydusctl: print fs read errors and total read data
  src/bin/nydusctl/commands.rs
Labels: anolis_test_fail

#1014 Fix a bug in rafs v6 introduced during code refactor
  rafs/src/metadata/direct_v6.rs
Labels: anolis_test_fail

#1006 Enhance nydus-test to support localfs backend of v2.2
  contrib/nydus-test/framework/rafs.py
  contrib/nydus-test/functional-test/test_api.py
  contrib/nydus-test/functional-test/test_image_compatibility.py
  contrib/nydus-test/functional-test/test_layered_image.py
  contrib/nydus-test/functional-test/test_nydus.py
  error/src/error.rs
  utils/src/filemap.rs
Labels: anolis_test_fail

#1018 rafs: avoid possible underflow in find_target_block()
  rafs/src/metadata/direct_v6.rs
Labels: anolis_test_pass

#1017 rafs: fix a underflow bug in rafs v6 implementation
  rafs/src/metadata/direct_v6.rs
Labels: anolis_test_fail

#1019 storage: return Ok(None) for check_range_ready_and_mark_pending () wh…
  storage/src/cache/state/blob_state_map.rs
Labels: anolis_test_pass

#1016 release: fix pipeline hang when compile for amd64
  Cross.toml
Labels: anolis_test_pass

#1020 storage: fix an assert failure related to zran
  storage/src/cache/cachedfile.rs
Labels: anolis_test_pass

#1021 smoke: DescartesIterator must return item when hasNext() returns true
  .github/workflows/smoke.yml
  smoke/tests/compatibility_test.go
  smoke/tests/image_test.go
  smoke/tests/native_layer_test.go
  smoke/tests/tool/iterator.go
Labels: anolis_testing

#1024 dep: remove unused dependencies
  Cargo.lock
  Cargo.toml
  utils/Cargo.toml
Labels: anolis_test_pass

#1023 storage: trim `\0` at the tail of blob id
  storage/src/device.rs
Labels: anolis_test_pass

#1025 docs: fix badges and update community description
  README.md
  misc/dingtalk.jpg
Labels: anolis_test_pass

#1026 nydusd: refine commandline help messages
  src/bin/nydusd/daemon.rs
  src/bin/nydusd/fs_service.rs
  src/bin/nydusd/fusedev.rs
  src/bin/nydusd/main.rs
Labels: anolis_test_pass

#1029 makefile: revert a change on default `install` prefix dir
  Makefile
Labels: anolis_test_pass

#1031 nydus-test: don't fetch iostats per file metrics
  contrib/nydus-test/functional-test/test_api.py
  contrib/nydus-test/nydusd_client.py
Labels: anolis_test_pass

#1032 build: clean up libz-sys stale cache for static build
  Makefile
Labels: anolis_test_pass

#1033 publish: prepare for publishing crates for v2.2
  Cargo.lock
  Cargo.toml
  api/Cargo.toml
  app/Cargo.toml
  blobfs/Cargo.toml
  clib/Cargo.toml
  error/Cargo.toml
  rafs/Cargo.toml
  storage/Cargo.toml
  utils/Cargo.toml
Labels: anolis_test_pass

#1035 builder: fix inconsistent chunk size for merge
  smoke/tests/native_layer_test.go
  src/bin/nydus-image/merge.rs
Labels: anolis_testing

#1027 Move generic code from nydusd into nydus crate
  Cargo.lock
  Cargo.toml
  src/bin/nydusd/api_server_glue.rs
  src/bin/nydusd/daemon.rs
  src/bin/nydusd/main.rs
  src/bin/nydusd/upgrade.rs
  src/bin/nydusd/virtiofs.rs
  src/daemon.rs
  src/fs_cache.rs
  src/fs_service.rs
  src/fusedev.rs
  src/lib.rs
  src/singleton.rs
  src/upgrade.rs
Labels: anolis_test_pass

#1036 smoke: fix lost compatibility test case
  .github/workflows/smoke.yml
  smoke/Makefile
  smoke/tests/compatibility_test.go
  smoke/tests/image_test.go
  smoke/tests/native_layer_test.go
  smoke/tests/tool/context.go
  smoke/tests/tool/util.go
  smoke/tests/zran_layer_test.go
Labels: anolis_test_pass

#1039 docs: update to use nydusify in zran doc
  docs/nydus-zran.md
Labels: anolis_test_pass

#1040 nydus: fix a build failure for macos
  src/lib.rs
  src/singleton.rs
Labels: anolis_test_pass
