Repository dragonflyoss/nydus, pull requests merged in 2023-04, with the labels that each got.

#1153 doc: update descriptions about nydus-snapshotter
  docs/containerd-env-setup.md
Labels: anolis_test_pass

#1199 service: add README for nydus-service
  README.md
  service/README.md
Labels: anolis_test_pass

#1203 action: upgrade golangci-lint to v1.51.2
  .github/workflows/convert.yml
  .github/workflows/smoke.yml
  smoke/tests/tool/iterator.go
  smoke/tests/tool/test/suite.go
Labels: anolis_test_pass

#1200 service: add coco feature in Cargo.toml
  service/Cargo.toml
Labels: anolis_test_pass

#1195 nydus: fix a possible panic caused by SubCmdArgs::is_present()
  src/lib.rs
Labels: anolis_test_pass

#1205 docs: add helm quickstart link to deploy Dragonfly+Nydus
  README.md
Labels: anolis_test_pass

#1208 rafs: fix a possible bug in v6_dirent_size()
  rafs/src/builder/core/v6.rs
Labels: anolis_test_pass, backport/v2.1, backport/v2.2

#1213 rafs: fix a regression caused by commit 2616fb2c0502e4
  rafs/src/metadata/direct_v6.rs
Labels: anolis_test_pass, backport/v2.1, backport/v2.2

#1218 service: add a functoin to help create fuse vfs backend
  service/src/fusedev.rs
  service/src/lib.rs
  src/bin/nydusd/main.rs
Labels: anolis_test_pass

#1215 Backports two bugfixes from master into stable/v2.2
  rafs/src/metadata/direct_v6.rs
  src/bin/nydus-image/core/node.rs
Labels: anolis_test_pass

#1217 [backport stable/v2.2] action: upgrade golangci-lint to v1.51.2
  .github/workflows/convert.yml
  .github/workflows/smoke.yml
  smoke/tests/tool/iterator.go
  smoke/tests/tool/test/suite.go
Labels: anolis_test_pass

#1192 Enhance file cache to encrypt data written to the cache file
  api/src/config.rs
  docs/samples/blob_cache_entry_configuration_v2.toml
  docs/samples/configuration_v2.toml
  rafs/src/metadata/cached_v5.rs
  rafs/src/metadata/direct_v5.rs
  rafs/src/metadata/direct_v6.rs
  rafs/src/metadata/layout/v5.rs
  rafs/src/metadata/md_v5.rs
  rafs/src/mock/mock_chunk.rs
  src/bin/nydus-image/unpack/pax/test.rs
  storage/Cargo.toml
  storage/src/cache/cachedfile.rs
  storage/src/cache/dummycache.rs
  storage/src/cache/filecache/mod.rs
  storage/src/cache/fscache/mod.rs
  storage/src/cache/mod.rs
  storage/src/cache/state/blob_state_map.rs
  storage/src/context.rs
  storage/src/device.rs
  storage/src/lib.rs
  storage/src/meta/chunk_info_v1.rs
  storage/src/meta/chunk_info_v2.rs
  storage/src/meta/mod.rs
  storage/src/test.rs
  utils/src/crypt.rs
Labels: anolis_test_pass

#1224 docs: add the tip for nydus-zran
  docs/nydus-zran.md
Labels: anolis_test_pass

#1222 rafs: optimize Node::name() to reduce image build time
  rafs/src/builder/core/node.rs
Labels: anolis_test_pass

#1227 misc: update toolchain to 1.68.2 and fix clippy warnings
  misc/musl-static/Dockerfile
  misc/nydus-smoke/Dockerfile
  rafs/src/lib.rs
  rafs/src/metadata/direct_v6.rs
  rafs/src/metadata/mod.rs
  rust-toolchain
  storage/src/factory.rs
  storage/src/meta/toc.rs
  utils/src/compress/mod.rs
  utils/src/crypt.rs
  utils/src/digest.rs
Labels: anolis_test_pass

#1229 feat: add more types of file to smoke
  smoke/tests/texture/layer.go
  smoke/tests/tool/file.go
  smoke/tests/tool/layer.go
Labels: anolis_test_pass, backport/v2.2

#1232 action: allow running smoke test for stable/* branch
  .github/workflows/smoke.yml
Labels: anolis_test_pass

#1235 action: fix smoke test for branch pattern
  .github/workflows/smoke.yml
Labels: anolis_testing

#1236 [backport] action: fix smoke test for branch pattern
  .github/workflows/ci.yml
Labels: anolis_testing, backport/v2.1

#1237 [backport] action: fix smoke test for branch pattern
  .github/workflows/smoke.yml
Labels: anolis_test_pass, backport/v2.2

#1233 rafs: minor optimization for tarfs builder
  rafs/src/builder/core/node.rs
  rafs/src/builder/core/tree.rs
Labels: anolis_test_pass

#1238 action: fix checkout on pull_request_target
  .github/workflows/smoke.yml
Labels: anolis_test_pass

#1242 docs: add codecov label in readme
  README.md
Labels: anolis_test_pass

#1243 action: add read-amount and read-count for benchmark
  misc/benchmark/bench.py
  misc/benchmark/benchmark.py
  misc/benchmark/benchmark_summary.sh
  misc/benchmark/metrics.py
Labels: anolis_testing

#1245 ctr-remote: update contaeinrd to v1.7.0 and fix lint error
  contrib/ctr-remote/cmd/main.go
  contrib/ctr-remote/commands/rpull.go
  contrib/ctr-remote/go.mod
  contrib/ctr-remote/go.sum
Labels: anolis_test_pass

#1206 feat: support the arg batch-size for small chunks mergence for nydusify
  contrib/nydusify/cmd/nydusify.go
  contrib/nydusify/pkg/converter/config.go
  contrib/nydusify/pkg/converter/converter.go
  contrib/nydusify/tests/e2e_test.go
  contrib/nydusify/tests/image_test.go
  contrib/nydusify/tests/nydusify.go
Labels: enhancement, anolis_test_pass

#1249 action: replace cargo test with cargo nextest in CI
  .github/workflows/smoke.yml
  Makefile
Labels: anolis_test_pass

#1252 action: fix checkout on pull_request_target
  .github/workflows/ci.yml
Labels: anolis_test_pass

#1251 action: make benchmark compare summary more clear
  misc/benchmark/bench.py
  misc/benchmark/benchmark_summary.py
Labels: anolis_test_pass

#1225 storage: refine the way to define compression algorithms
  storage/src/meta/toc.rs
Labels: anolis_test_pass

#1211 storage: refine the way to implement BlobIoChunk
  rafs/src/fs.rs
  rafs/src/metadata/cached_v5.rs
  rafs/src/metadata/direct_v5.rs
  rafs/src/metadata/direct_v6.rs
  rafs/src/metadata/layout/v5.rs
  rafs/src/metadata/md_v5.rs
  rafs/src/metadata/md_v6.rs
  rafs/src/metadata/mod.rs
  rafs/src/mock/mock_inode.rs
  storage/src/cache/cachedfile.rs
  storage/src/cache/dummycache.rs
  storage/src/cache/mod.rs
  storage/src/device.rs
Labels: anolis_test_pass

#1256 contrib: support nydus-overlayfs and ctr-remote on different platforms
  contrib/ctr-remote/Makefile
  contrib/nydus-overlayfs/Makefile
Labels: anolis_testing
