Repository dragonflyoss/nydus, pull requests merged in 2023-05, with the labels that each got.

#1266 misc: reorganize the configuration file of nydusd
  docs/nydusd.md
  misc/configs/nydusd-blob-cache-entry-configuration-v2.toml
  misc/configs/nydusd-blob-cache-entry.toml
  misc/configs/nydusd-boostrap-blob-cache-entry.json
  misc/configs/nydusd-config-v2.toml
  misc/configs/nydusd-config.json
  misc/example/nydusd-config.json
Labels: anolis_test_pass

#1277 contrib: support nydus-overlayfs and ctr-remote on different platforms
  contrib/ctr-remote/Makefile
  contrib/nydus-overlayfs/Makefile
Labels: anolis_test_pass, backport/v2.1

#1278 contrib: support nydus-overlayfs and ctr-remote on different platforms
  contrib/ctr-remote/Makefile
  contrib/nydus-overlayfs/Makefile
Labels: anolis_test_pass, backport/v2.2

#1280 smoke: no need to run vet and lint
  smoke/Makefile
Labels: anolis_test_pass

#1281 action:clean cache after branch closes
  .github/workflows/clean-cache.yml
Labels: anolis_testing

#1283 cargo: update fuse-backend-rs dependency
  Cargo.lock
Labels: anolis_testing

#1282 action: benchmark add description
  .github/workflows/benchmark.yml
Labels: anolis_test_pass

#1287 app: merge crate nydus-app into crate nydus
  Cargo.lock
  Cargo.toml
  app/CHANGELOG.md
  app/CODEOWNERS
  app/Cargo.toml
  app/LICENSE
  app/README.md
  blobfs/Cargo.toml
  blobfs/src/lib.rs
  build.rs
  src/bin/nydus-image/main.rs
  src/bin/nydusd/main.rs
  src/lib.rs
  src/logger.rs
  src/signal.rs
  tests/smoke.rs
Labels: anolis_test_pass

#1286 docs: add pull request and issue templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: anolis_test_pass

#1298 builder: delay free data structure to reduce image build time
  rafs/src/builder/core/tree.rs
  rafs/src/builder/directory.rs
  rafs/src/builder/stargz.rs
  rafs/src/builder/tarball.rs
  src/bin/nydus-image/main.rs
  utils/src/lib.rs
Labels: anolis_test_pass

#1299 error: merge crate nydus-error into nydus-utils and nydus-api
  Cargo.lock
  Cargo.toml
  api/Cargo.toml
  api/src/config.rs
  api/src/error.rs
  api/src/http.rs
  api/src/http_handler.rs
  api/src/lib.rs
  error/CHANGELOG.md
  error/CODEOWNERS
  error/Cargo.toml
  error/LICENSE-APACHE
  error/LICENSE-BSD-3-Clause
  error/README.md
  error/src/lib.rs
  rafs/Cargo.toml
  rafs/src/lib.rs
  service/Cargo.toml
  service/src/lib.rs
  src/bin/nydusd/main.rs
  src/lib.rs
  storage/Cargo.toml
  storage/src/lib.rs
  utils/Cargo.toml
  utils/src/lib.rs
  utils/src/logger.rs
  utils/src/metrics.rs
Labels: anolis_test_pass

#1302 smoke: use v2.1.6 instead of v2.1.4
  .github/workflows/smoke.yml
  smoke/tests/compatibility_test.go
Labels: anolis_test_fail
