Repository dragonflyoss/nydus, pull requests merged in 2023-06, with the labels that each got.

#1308 builder: set the default compression algorithm for meta ci to lz4
  rafs/src/builder/core/blob.rs
Labels: anolis_test_pass

#1309 Rafs: Add missing prefix of hex
  rafs/src/metadata/md_v5.rs
  rafs/src/metadata/md_v6.rs
Labels: anolis_test_pass

#1293 ci(release): add macos arm64 artifact
  .github/workflows/release.yml
Labels: anolis_test_pass

#1324 ci(release): fix macos nydusd rust target
  .github/workflows/release.yml
  Cargo.lock
Labels: anolis_testing

#1319 fix some issue about the subcommand mount of nydusify
  contrib/nydusify/cmd/nydusify.go
  contrib/nydusify/pkg/checker/rule/filesystem.go
  contrib/nydusify/pkg/viewer/viewer.go
Labels: anolis_test_pass

#1330 Nydusify-fix(stable/v2.1): fix some bug about the subcommand mount of nydusify
  contrib/nydusify/cmd/nydusify.go
  contrib/nydusify/pkg/checker/rule/filesystem.go
  contrib/nydusify/pkg/viewer/viewer.go
Labels: anolis_test_pass, backport/v2.1

#1335 gha:add some descriptions for convert ci
  .github/workflows/convert.yml
Labels: anolis_test_pass

#1336 nydusify: update the doc of nydusify about the subcommand mount
  docs/nydusify.md
Labels: anolis_test_pass

#1326 rafs: add special handling of invalid zero blob index
  rafs/src/metadata/direct_v6.rs
  rafs/src/metadata/layout/v6.rs
Labels: anolis_test_pass
