Repository dragonflyoss/nydus, pull requests merged in 2023-03, with the labels that each got.

#1120 docs: add zran-indexed demo and ADOPTERS.md
  ADOPTERS.md
  docs/nydus-fscache.md
  docs/nydus-zran.md
Labels: anolis_testing

#1119 docs: Add Docker(moby) integration
  README.md
  docs/docker-env-setup.md
Labels: anolis_test_pass

#1122 dep: prepare for v2.2 release
  contrib/nydusify/go.mod
  contrib/nydusify/go.sum
  smoke/go.mod
  smoke/go.sum
Labels: anolis_testing

#1126 api: prepare for publishing v0.2.2
  Cargo.toml
  api/Cargo.toml
  service/Cargo.toml
Labels: anolis_test_pass

#1123 deps: bump tempfile version to 3.4.0 to fix some security vulnerabilities
  Cargo.lock
  contrib/nydus-backend-proxy/Cargo.lock
  storage/Cargo.toml
Labels: anolis_test_pass

#1130 nydus-image: fix a underflow issue in get_compressed_size()
  src/bin/nydus-image/core/blob.rs
Labels: anolis_test_pass

#1125 Prepare for exposing nydus images as block devices
  api/src/config.rs
  src/bin/nydus-image/core/bootstrap.rs
Labels: anolis_test_pass

#1133 nydus-image: fix a underflow issue in get_compressed_size()
  src/bin/nydus-image/core/blob.rs
Labels: anolis_test_pass

#1140 readme: add a very brief section to introduce image optimizer
  README.md
Labels: anolis_test_pass

#1135 Minor improvements to nydus-image
  src/bin/nydus-image/builder/directory.rs
  src/bin/nydus-image/builder/stargz.rs
  src/bin/nydus-image/builder/tarball.rs
  src/bin/nydus-image/core/blob_compact.rs
  src/bin/nydus-image/core/context.rs
  src/bin/nydus-image/core/node.rs
  src/bin/nydus-image/main.rs
  src/bin/nydus-image/merge.rs
Labels: anolis_test_pass

#1139 Export Nydus images as block devices by using NBD
  Cargo.lock
  Cargo.toml
  api/src/config.rs
  api/src/http.rs
  docs/samples/blob_cache_entry.toml
  rafs/src/metadata/direct_v6.rs
  rafs/src/metadata/layout/v6.rs
  rafs/src/metadata/md_v6.rs
  rafs/src/metadata/mod.rs
  service/Cargo.toml
  service/src/blob_cache.rs
  service/src/block_device.rs
  service/src/block_nbd.rs
  service/src/daemon.rs
  service/src/fs_cache.rs
  service/src/lib.rs
  service/src/singleton.rs
  src/bin/nydusd/main.rs
  tests/texture/blobs/be7d77eeb719f70884758d1aa800ed0fb09d701aaec469964e9d54325f0d5fef
  tests/texture/bootstrap/rafs-v6-2.2.boot
Labels: anolis_test_pass

#1141 Move RAFS filesystem builder into nydus-rafs crate
  Cargo.lock
  Cargo.toml
  rafs/Cargo.toml
  rafs/src/builder/compact.rs
  rafs/src/builder/core/blob.rs
  rafs/src/builder/core/bootstrap.rs
  rafs/src/builder/core/chunk_dict.rs
  rafs/src/builder/core/context.rs
  rafs/src/builder/core/feature.rs
  rafs/src/builder/core/layout.rs
  rafs/src/builder/core/mod.rs
  rafs/src/builder/core/node.rs
  rafs/src/builder/core/overlay.rs
  rafs/src/builder/core/prefetch.rs
  rafs/src/builder/core/tree.rs
  rafs/src/builder/core/v5.rs
  rafs/src/builder/core/v6.rs
  rafs/src/builder/directory.rs
  rafs/src/builder/mod.rs
  rafs/src/builder/stargz.rs
  rafs/src/builder/tarball.rs
  rafs/src/lib.rs
  rafs/src/metadata/chunk.rs
  rafs/src/metadata/inode.rs
  rafs/src/metadata/layout/mod.rs
  rafs/src/metadata/layout/v6.rs
  rafs/src/metadata/mod.rs
  src/bin/nydus-image/core/bootstrap.rs
  src/bin/nydus-image/core/feature.rs
  src/bin/nydus-image/core/node.rs
  src/bin/nydus-image/inspect.rs
  src/bin/nydus-image/main.rs
  src/bin/nydus-image/merge.rs
  src/bin/nydus-image/stat.rs
  src/bin/nydus-image/unpack/mod.rs
  src/bin/nydus-image/unpack/pax.rs
  src/bin/nydus-image/validator.rs
  utils/src/lib.rs
  utils/src/trace.rs
Labels: anolis_test_pass

#1149 upgrad fuse-backend-rs to 0.10.2
  Cargo.lock
  service/Cargo.toml
Labels: anolis_test_pass

#1150 rafs: fix amplify can not be skipped.
  rafs/src/fs.rs
Labels: anolis_test_pass

#1146 nydusify: fix pulling all platforms of source image
  contrib/nydusify/cmd/nydusify.go
  contrib/nydusify/go.mod
  contrib/nydusify/go.sum
  contrib/nydusify/pkg/converter/config.go
  contrib/nydusify/pkg/converter/converter.go
  contrib/nydusify/pkg/converter/provider/ported.go
  contrib/nydusify/pkg/converter/provider/provider.go
  contrib/nydusify/pkg/provider/remote.go
  smoke/go.mod
  smoke/go.sum
Labels: anolis_test_pass

#1147 Introduce new tarfs mode to Nydus
  rafs/src/builder/core/blob.rs
  rafs/src/builder/core/bootstrap.rs
  rafs/src/builder/core/context.rs
  rafs/src/builder/core/node.rs
  rafs/src/builder/core/v6.rs
  rafs/src/builder/mod.rs
  rafs/src/builder/tarball.rs
  rafs/src/fs.rs
  rafs/src/metadata/direct_v6.rs
  rafs/src/metadata/layout/v6.rs
  rafs/src/metadata/mod.rs
  service/src/blob_cache.rs
  service/src/block_device.rs
  service/src/block_nbd.rs
  src/bin/nydus-image/main.rs
  storage/src/cache/cachedfile.rs
  storage/src/cache/filecache/mod.rs
  storage/src/cache/fscache/mod.rs
  storage/src/device.rs
  storage/src/meta/mod.rs
  utils/src/lib.rs
  utils/src/reader.rs
Labels: anolis_test_pass

#1156 rafs: define dedicated RafsV6Inode to reduce memory consumption
  rafs/src/builder/core/bootstrap.rs
  rafs/src/builder/core/node.rs
  rafs/src/builder/core/v6.rs
  rafs/src/builder/stargz.rs
  rafs/src/builder/tarball.rs
  rafs/src/metadata/cached_v5.rs
  rafs/src/metadata/inode.rs
  rafs/src/metadata/layout/v5.rs
  rafs/src/metadata/layout/v6.rs
  rafs/src/mock/mock_inode.rs
Labels: anolis_test_pass

#1151 Enhance `nydus-image merge` to support tarfs
  rafs/src/builder/compact.rs
  rafs/src/builder/core/blob.rs
  rafs/src/builder/core/bootstrap.rs
  rafs/src/builder/core/chunk_dict.rs
  rafs/src/builder/core/context.rs
  rafs/src/builder/core/layout.rs
  rafs/src/builder/core/prefetch.rs
  rafs/src/builder/core/v6.rs
  rafs/src/builder/merge.rs
  rafs/src/builder/mod.rs
  rafs/src/metadata/chunk.rs
  rafs/src/metadata/direct_v6.rs
  rafs/src/metadata/mod.rs
  src/bin/nydus-image/main.rs
Labels: anolis_test_pass

#1155 rafs: only enable digest validate based on configuration
  rafs/src/builder/core/bootstrap.rs
  rafs/src/builder/core/chunk_dict.rs
  rafs/src/builder/merge.rs
  rafs/src/fs.rs
  rafs/src/metadata/mod.rs
  service/src/blob_cache.rs
  src/bin/nydus-image/inspect.rs
  src/bin/nydus-image/main.rs
  src/bin/nydus-image/stat.rs
  src/bin/nydus-image/unpack/mod.rs
  src/bin/nydus-image/validator.rs
Labels: anolis_test_pass

#1158 Enhance FUSE implementation to support RAFS in TARFS mode
  rafs/src/fs.rs
  rafs/src/metadata/chunk.rs
  rafs/src/metadata/direct_v6.rs
Labels: anolis_test_pass

#1161 ci test: fix bug of compiling nydus-snapshotter
  tests/bats/compile_nydus_snapshotter.bats
Labels: anolis_test_pass

#1163 nydusify: fix oci media type handle
  contrib/nydusify/go.mod
  contrib/nydusify/go.sum
  smoke/go.mod
  smoke/go.sum
Labels: anolis_test_pass

#1164 nydusify: cleanup work directory when conversion finish
  contrib/nydusify/pkg/converter/converter.go
Labels: anolis_testing

#1165 rafs: fix a assertion failure in prefetch list generation
  rafs/src/builder/core/v6.rs
Labels: anolis_testing

#1166 rafs: git rid of several unimplemented()
  rafs/src/metadata/inode.rs
Labels: anolis_test_pass

#1167 service: fix compilation failures on macos
  service/Cargo.toml
  service/src/daemon.rs
  service/src/lib.rs
  service/src/singleton.rs
Labels: anolis_test_pass

#1168 rafs: fix incorrect blob id in merged TARFS
  rafs/src/builder/merge.rs
Labels: anolis_test_pass

#1172 fix: stable/XXX branch not run ci
  .github/workflows/smoke.yml
Labels: anolis_test_pass, backport/v2.2

#1169 service: clean clippy warnings for macos
  Cargo.toml
  service/src/lib.rs
Labels: anolis_test_pass

#1171 backport fix/feature to stable 2.2
  .github/workflows/smoke.yml
  Cargo.lock
  contrib/nydus-backend-proxy/Cargo.lock
  contrib/nydusify/cmd/nydusify.go
  contrib/nydusify/go.mod
  contrib/nydusify/go.sum
  contrib/nydusify/pkg/converter/config.go
  contrib/nydusify/pkg/converter/converter.go
  contrib/nydusify/pkg/converter/provider/ported.go
  contrib/nydusify/pkg/converter/provider/provider.go
  contrib/nydusify/pkg/provider/remote.go
  rafs/src/fs.rs
  rafs/src/metadata/mod.rs
  smoke/go.mod
  smoke/go.sum
  smoke/tests/native_layer_test.go
  smoke/tests/texture/layer.go
  smoke/tests/tool/layer.go
  src/bin/nydus-image/main.rs
  src/bin/nydus-image/merge.rs
  storage/Cargo.toml
  tests/bats/compile_nydus_snapshotter.bats
Labels: anolis_test_pass, backport/v2.2

#1121 service: Add a README.md to nydus-service
  README.md
  service/README.md
Labels: anolis_test_pass, backport/v2.2

#1178 nydus-image: print mapped block address when inspecting blob info
  src/bin/nydus-image/inspect.rs
Labels: anolis_test_pass

#1177 nydus: fix a possible panic caused by SubCmdArgs::is_present()
  src/lib.rs
Labels: anolis_test_pass, backport/v2.2

#1159 Add `export` subcommand to `nydus-image`
  Cargo.toml
  service/src/block_device.rs
  src/bin/nydus-image/main.rs
Labels: anolis_test_pass

#1184 rafs: fix a incorrect mapped_blkaddr for multi layer images
  rafs/src/builder/core/v6.rs
Labels: anolis_test_pass

#1183 docs: polish and simplify README.md
  README.md
Labels: documentation, anolis_testing

#1176 Add verity digests for exported block device
  service/src/block_device.rs
  src/bin/nydus-image/main.rs
  utils/src/filemap.rs
  utils/src/lib.rs
  utils/src/verity.rs
Labels: anolis_test_pass

#1188 contrib: upgrade runc to v1.1.5
  contrib/ctr-remote/go.mod
  contrib/ctr-remote/go.sum
  contrib/nydusify/go.mod
  contrib/nydusify/go.sum
Labels: anolis_test_pass

#1189 macos: fix a build failure
  src/bin/nydus-image/main.rs
Labels: anolis_test_pass
